### ISSUE TITLE
username has to be encoded in swtich-to-grafana-admin.sh script

### ISSUE THREAD

**Issue by changwoojung** [open-cluster-management/multicluster-observability-operator#588]
Followed the instruction to set up the Grafana developer instance.
https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.2/html/observing_environments/observing-environments-intro#designing-your-grafana-dashboard

When tried with "switch-to-grafana-admin.sh", I encountered some issue as my id is "IAM#changwoo" since I installed RHACM on ROKS (Red Hat OpenShift on IBM Cloud).

Basically, "#" made things complicated. 

Suggesting the fix something like this at line 70,

 **encoded_user_name=`echo -n $user_name | jq -sRr '@uri'`**
  userID=`$curlCMD -s -X GET -H "Content-Type: application/json" -H "X-Forwarded-User: $XForwardedUser" 127.0.0.1:3001/api/users/lookup?loginOrEmail=$encoded_user_name | $PYTHON_CMD -c "import sys, json; print(json.load(sys.stdin)['id'])" 2>/dev/null`

orgID=`$curlCMD -s -X GET -H "Content-Type: application/json" -H "X-Forwarded-User:$XForwardedUser" 127.0.0.1:3001/api/users/lookup?loginOrEmail=$encoded_user_name | $PYTHON_CMD -c "import sys, json; print(json.load(sys.stdin)['orgId'])" 2>/dev/null`

**Comment by songleo** [comment]
fixed in https://github.com/open-cluster-management/multicluster-observability-operator/pull/662 thanks.
